apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_SCOPE_NAMESPACE
          value: "{{ .Values.manager.watchNamespace }}"
        - name: LOCAL_REGISTRY
          value: {{ .Values.global.imageRegistry | default "docker.io" }}
        - name: NAMESPACE_OVERRIDE
          value: {{ .Values.namespaceOverride | default "radondb" }}
        - name: RABBITMQ_IMAGE
          value: {{ .Values.cluster.rabbitmq.image | default "rabbitmq" }}
        - name: RABBITMQ_VERSION
          value: {{ .Values.cluster.rabbitmq.tag | default "3.11.13-management" }}
        {{- if .Values.global.imagePullSecrets }}
        - name: DEFAULT_IMAGE_PULL_SECRETS
          value: {{ .Values.global.imagePullSecrets }}
        {{- end }}
        image: "{{ .Values.global.imageRegistry | default "docker.io" }}{{"/"}}{{ .Values.namespaceOverride | default "radondb" }}{{"/"}}{{ .Values.manager.image }}:{{ .Values.manager.tag | default .Chart.AppVersion }}"
        name: rabbitmq-cluster-operator
        ports:
        - containerPort: 9782
          name: metrics
          protocol: TCP
        resources:
          {{- toYaml .Values.manager.resources | nindent 12 }}
      serviceAccountName: rabbitmq-cluster-operator
      terminationGracePeriodSeconds: 10

