global:
  imageRegistry: docker.io
  imagePullSecrets: []

nodeSelector: {}
tolerations: []
manager:
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 200m
      memory: 500Mi
  image: rabbitmq-operator
  ## tag default uses appVersion from Chart.yaml, to override specify tag tag: "v1.1"
  tag: "2.2.3"
  # If a watchNamespace is specified, the manager's cache will be restricted to
  # watch objects in the desired namespace. Defaults is to watch all namespaces.
  watchNamespace:

localRegistry: docker.io
namespaceOverride: radondb
pullPolicy: Always

cluster:
  rabbitmq:
    image: rabbitmq
    tag: "3.11.13-management"
